# Generated by Django 3.0.4 on 2020-04-02 13:31

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('street', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('zip', models.IntegerField(blank=True, default=None, null=True)),
                ('website', models.URLField(blank=True, default=None, max_length=250, null=True)),
                ('phone', models.IntegerField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('opening_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=None, max_length=56, null=True)),
                ('opening_time', models.TimeField(blank=True, default=None, null=True)),
                ('closing_time', models.TimeField(blank=True, default=None, null=True)),
                ('price_level', models.CharField(choices=[('LOW', '$'), ('MEDIUM', '$$'), ('HIGH', '$$$')], default=('MEDIUM', '$$'), max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='categories.Category')),
            ],
        ),
    ]
