# Generated by Django 3.0.4 on 2020-04-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='price_level',
            new_name='price_level1',
        ),
    ]
