# Generated by Django 3.0.4 on 2020-03-31 12:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200331_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='opening_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=56),
        ),
    ]
