# Generated by Django 3.0.4 on 2020-04-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200402_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='price_level1',
            new_name='price_level',
        ),
    ]
