# Generated by Django 3.0.5 on 2020-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationtoken', '0002_auto_20200402_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailvalidation', models.TextField()),
            ],
        ),
    ]
