# Generated by Django 3.0.4 on 2020-03-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200331_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='new',
        ),
    ]
