# Generated by Django 3.0.4 on 2020-03-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='all_likes_of_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='delete_review',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='get_list_of_user_post_commented',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='like_review',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='new',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='specific_review',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='unlike_review',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='update_review',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
