# Generated by Django 3.0.4 on 2020-03-31 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200331_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='all_likes_of_user',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='delete_review',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='get_list_of_user_post_commented',
        ),
        migrations.RemoveField(
            model_name='review',
            name='like_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='new',
        ),
        migrations.RemoveField(
            model_name='review',
            name='specific_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='unlike_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='update_review',
        ),
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='review',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_content',
            field=models.TextField(default='enter text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.TextField(default='Restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.TextField(default='Username'),
        ),
    ]
