# Generated by Django 3.0.4 on 2020-03-31 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200331_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
